### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by skeedy2** [tripod31/foo_lyricsource#3]
Hi, thank you for your effort

I cannot install this, although I followed your instructions.
I put foo_lyricsouce.dll in the components folder
I put iconv.dll and libxml2 in the foobar2000 folder
I put get_lyric.exe into the foobar2000 folder.

I can't get_lyrics.exe to work, when I test it, it says this

> Traceback <most recent call last>:
File "<string>", line 38, in <module>
PermissionError: {Errno 13} Permission denied: 'get_lyric.log"
get_lyric returned -1

Can you please help me? Maybe this is because I use windows 8.1?

**Comment by tripod31** [comment]
For test,I set the permission of get_lyric.log to read-only,from windows explorer.Then I test get_lyrics.exe,and got same error.
delete get_lyric.log,and please test it again.

**Comment by skeedy2** [comment]
Hi, where is the get_lyric.log? It is not in the foobar directory where I put get_lyrics.exe

 
 

Sent: Saturday, February 27, 2021 at 8:39 AM

**Comment by tripod31** [comment]
The error occurs when the script writes log.Maybe Script tries to write log to the directory like "C:/promgram files/foobar2000/".The directory requires special permission to write files.
I added argument to script,to specifies path to write log.
to test this,

1)go to test branch.
https://github.com/tripod31/get_lyric/tree/test
2)copy get_lyric.exe
3)copy get_lyric.cnf.sample to get_lyric.cnf,in the same directory as get_lyric.exe resides.
4)edit get_lyric.cnf
[settings]
log_path=C:\Users\username\Documents

Change "C:\Users\username\Documents" acoording to your environment.it should be writable directry,

By the way,I tested the script today,I found only two sites can work with the script.So maybe number of songs that can retrieve thier lyrics,gets fewer than before.

**Comment by skeedy2** [comment]
hi, thanks, it works now. i couldn't get the motorhead song to work, but another song worked fine.

 

actually, i'm using this so I can try to work https://github.com/lukaszsulek/get_lyric

 

thanks so much

 
 

Sent: Saturday, February 27, 2021 at 9:31 PM

**Comment by skeedy2** [comment]
have you tried this? now both your .exe and the python script work in cmd, but foobar still doesn't return results. very annoying

**Comment by skeedy2** [comment]
hi, thanks, I got it to work.

I downloaded this so I could use https://github.com/lukaszsulek/get_lyric

To use this you have to put your get_lyric.exe and the other developer's get_lyric.py in the same directory, this stopped yours from working

I don't know how to get get_lyric working, but yours works fine. do you know what the problem is?

thanks again, you are the best
